// Centralize all event names
// MR
export const EVENTS = {
  TICKET_CREATED: "TICKET_CREATED",
  TICKET_UPDATED: "TICKET_UPDATED",
  TICKET_STATUS_CHANGED: "TICKET_STATUS_CHANGED",
  TICKET_DELETED: "TICKET_DELETED",
  TICKETS_CHANGED: "TICKETS_CHANGED",
} as const;

export type EventName = keyof typeof EVENTS;
// END MR
