services:
  backend:
    image: nextone4/nextone-back:latest
    ports:
      - "4005:4005"
    env_file:
      - ./.env
    healthcheck:
      test:
        - CMD-SHELL
        - "curl -f http://localhost:4005/graphql?query=%7B__typename%7D -H 'Apollo-Require-Preflight: true' || exit 1"
      interval: 10s
      timeout: 30s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "wait-for-healthcheck.sh"]
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /src
          ignore:
            - node_modules/
  db:
    image: postgres
    restart: always
    env_file:
      - ./db.env
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d nextone-db -U utilisateur"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - gcdatabase:/var/lib/postgresql/data
  db_test:
    image: postgres
    restart: always
    env_file:
      - ./db_test.env
    ports:
      - 5436:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d nextone-db-test -U utilisateur"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - gcdatabase-test:/var/lib/postgresql/data
volumes:
  gcdatabase:
  gcdatabase-test:
