FROM node:lts-alpine

WORKDIR /app

COPY package.json .
COPY tsconfig.json .
RUN npm install --only=production

RUN apk --update --no-cache add curl

COPY dist/ ./dist

COPY scripts/wait-for-healthcheck-prod.sh /usr/local/bin/wait-for-healthcheck-prod.sh
COPY scripts/wait-for-healthcheck-staging.sh /usr/local/bin/wait-for-healthcheck-staging.sh

RUN chmod +x /usr/local/bin/wait-for-healthcheck-prod.sh