services:
  backend:
    image: nextone4/nextone-back:latest
    container_name: nextone-back
    ports:
      - "4005:4005"
    env_file:
      - ./nextone-back/.env
    healthcheck:
      test:
        - CMD-SHELL
        - "curl -f http://localhost:4005/graphql?query=%7B__typename%7D -H 'Apollo-Require-Preflight: true' || exit 1"
      interval: 10s
      timeout: 30s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "wait-for-healthcheck-prod.sh"]
    
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /src
          ignore:
            - node_modules/
  db:
    image: postgres
    restart: always
    env_file:
      - ./nextone-back/db.env
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d nextone-db -U utilisateur"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - gcdatabase:/var/lib/postgresql/data
  frontend:
    image: nextone4/nextone-front:latest
    container_name: nextone-front
    ports:
      - "4000:4000"
    env_file:
      - ./nextone-front/.env
  nginx:
    image: nginx:1.21.3
    depends_on:
      - backend
      - db
      - frontend
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
  gcdatabase: