scalar DateTime

type Company {
  id: ID!
  name: String!
  address: String!
  postalCode: String!
  city: String!
  siret: String!
  email: String!
  phone: String!
  services: [Service!]!
  managers: [Manager!]!
  settings: [Setting!]!
  createdAt: DateTime!
  updatedAt: DateTime!
}


type Query {
  companies(pagination: PaginationInput): [Company!]!
  company(id: ID!): Company
  companiesByProperties(fields: CompanyByPropertiesInput!): [Company!]!
}

type Mutation {
  createCompany(data: CreateCompanyInput!): Company!
  deleteCompany(id: ID!): DeleteResponseCompany!
  updateCompany(data: UpdateCompanyInput!): Company!
}

type DeleteResponseCompany {
  message: String!
  success: Boolean!
}
input CompanyByPropertiesInput {
  name: String
  address: String
  postalCode: String
  city: String
  siret: String
  email: String
  phone: String
  pagination: PaginationInput
  createdAt: DateTime
  updatedAt: DateTime
}

input CreateCompanyInput {
  name: String!
  address: String!
  postalCode: String!
  city: String!
  siret: String!
  email: String!
  phone: String!
}

input UpdateCompanyInput {
  id: ID!
  name: String
  address: String
  postalCode: String
  city: String
  siret: String
  email: String
  phone: String
}


