scalar DateTime

type Company {
  id: ID!
  name: String!
  address: String!
  postalCode: String!
  city: String!
  siret: String!
  email: String!
  phone: String!
  services: [Service!]!
  createdAt: DateTime!
  updatedAT: DateTime!
}


type Query {
  companies: [Company!]!
  company(id: ID!): Company
}

type Mutation {
  createCompany(data: CreateCompanyInput!): Company!
  deleteCompany(id: ID!): DeleteResponseCompany!
  updateCompany(data: UpdateCompanyInput!): Company!
}

type DeleteResponseCompany {
  content: String!
  success: Boolean!
}

input CreateCompanyInput {
  name: String!
  address: String!
  postalCode: String!
  city: String!
  siret: String!
  email: String!
  phone: String!
}

input UpdateCompanyInput {
  id: ID!
  name: String
  address: String
  postalCode: String
  city: String
  siret: String
  email: String
  phone: String
}


