scalar DateTime

enum ConnectionEnum {
  Login
  Logout
}

type ConnectionLog {
  id: ID!
  type: ConnectionEnum!
  manager: ManagerWithoutPassword!
  createdAt: DateTime!
}

 type Query {
  getConnectionLogs: [ConnectionLog!]!
  getLoginLogs: [ConnectionLog!]!
  getLogoutLogs: [ConnectionLog!]!
  getEmployeeConnectionLogs(managerId: String!): [ConnectionLog!]!
}

 type Mutation {
  createConnectionLog(type: ConnectionEnum!, managerId: UUID!): ConnectionLog!
}
