scalar DateTime

enum ConnectionEnum {
  Login
  Logout
}

type ConnectionLog {
  id: ID!
  type: ConnectionEnum!
  manager: Manager!
  createdAt: DateTime!
}

type ConnectionLogsPaginatedResult {
  items: [ConnectionLog!]!
  totalCount: Int!
}


type Query {
  connectionLogs(pagination: PaginationInput): ConnectionLogsPaginatedResult!
  loginLogs(pagination: PaginationInput): ConnectionLogsPaginatedResult!
  logoutLogs(pagination: PaginationInput): ConnectionLogsPaginatedResult!
  employeeConnectionLogs(managerId: String!, pagination: PaginationInput): ConnectionLogsPaginatedResult!

}

 type Mutation {
  createConnectionLog(type: ConnectionEnum!, managerId: UUID!): ConnectionLog!
}
