scalar Timestamp
scalar DateTime

type Invitation {
  id: UUID!
  email: String!
  role: ManagerRole!
  token: String!
  tokenExpiration: Timestamp!
  company: Company!
  createdAt: DateTime!
  updatedAt: DateTime!
}
type SortedInvitations{
  pending: [Invitation!]!
  expired: [Invitation!]!
}

type Query {
  invitation(id: UUID!): Invitation
  invitations: [Invitation!]!
  sortedInvitations: SortedInvitations!
}

type Mutation {
  createInvitation(args: CreateInvitationInput!): Invitation!
  updateInvitation(args: UpdateInvitationInput!): Invitation
  renewInvitation(id: UUID!): Invitation!
  deleteInvitation(id: UUID!): DeleteResponse!
}

input CreateInvitationInput {
  email: String!
  role: ManagerRole!
}

input UpdateInvitationInput {
  id: UUID!
  email: String @constraint(pattern: "email", maxLength: 255)
  role: ManagerRole
}