scalar DateTime

enum ManagerRole {
  OPERATOR
  ADMIN
  SUPER_ADMIN
}

type CheckToken {
  email: String
  id: ID
  firstName: String
  lastName: String
}

type Manager {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  role: ManagerRole!
  isGloballyActive: Boolean!
  authorizations: [Authorization!]!
  company: Company!
  connectionLogs: [ConnectionLog!]!
  ticketLogs: [TicketLog!]!
  createdAt: DateTime!
  updatedAt: DateTime!
  resetToken: String
  resetTokenExpiration: DateTime
}

type Auth {
  manager: Manager
  token: String
}

type Message {
  message: String
  success: Boolean
}

type Query {
  managers: [Manager!]
  manager(id: ID!): Manager!
  login(infos: InputLogin!): Auth
  logout: Message!
  checkToken: CheckToken
}

type Mutation {
  createManager(infos: InputRegister!): Manager!
  deleteManager(id: ID!): Message!
  updateManager(id: ID!, data: UpdateManagerInput!): Manager!
  # associateManagerAtService(managerId: ID!, serviceId: ID!): Message!
  # dissociateManagerFromService(managerId: ID!, serviceId: ID!): Message!
  toggleGlobalAccessManager(id: UUID!): Message!
  askResetPassword(email: String!): Message!
  resetPassword(args: ResetPasswordInput!): Message!
}

input InputRegister {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
  role: ManagerRole = OPERATOR
  isGloballyActive: Boolean = FALSE
  companyId: UUID!
}

input InputLogin {
  email: String!
  password: String!
}

input UpdateManagerInput {
  firstName: String
  lastName: String
  role: ManagerRole
}

input ResetPasswordInput {
  resetToken : String!
  newPassword: String!
  confirmNewPassword: String!
  email: String!
}

