# service.gql

scalar UUID
scalar DateTime

####### Types
type Service {
  id: UUID!
  name: String!
  createdAt: DateTime!
  updatedAt: String!
}

type Query {
  services: [Service!]!
  service(id: UUID!): Service
}
type Mutation {
  createService(data: CreateServiceInput!): Service!
  updateService(id: UUID!, data: UpdateServiceInput!): ServiceResponse!
  deleteService(id: UUID!): ServiceResponse!
  
}

type ServiceResponse {
  message: String!
  success: Boolean!
}


### Input
input CreateServiceInput {
  name: String!
}

input UpdateServiceInput {
  name: String
}