scalar DateTime


type Setting {
  id: ID!
  name: String!
  value: String!
  company: Company!
  createdAt: DateTime
  updatedAt: DateTime
}

type Query {
  settings(pagination: PaginationInput): [Setting!]!
  setting(id: ID!): Setting
  settingsByProperties(fields: SettingsByPropertiesInput!): [Setting!]!
}

type DeleteResponseSetting {
  message: String!
  success: Boolean!
}

input SettingsByPropertiesInput {
  name: String
  value: String
  companyId: UUID
  pagination: PaginationInput
  createdAt: DateTime
  updatedAt: DateTime
}

type Mutation {
  createSetting(data: CreateSettingInput!): Setting!
  deleteSetting(id: ID!): DeleteResponseSetting!
  updateSetting(data: UpdateSettingInput!): Setting
}

input CreateSettingInput {
  name: String!
  value: String!
  companyId: UUID!
}

input UpdateSettingInput {
  id: ID!
  name: String
  value: String
}


