type Setting {
  id: ID!
  name: String!
  createdAt: String
  updatedAt: String
}

type Query {
  settings: [Setting!]!
  setting(id: ID!): Setting
}

type Mutation {
  createSetting(data: CreateSettingInput!): Setting!
  deleteSetting(id: ID!): Boolean!
  updateSetting(data: UpdateSettingInput!): Setting
}

input CreateSettingInput {
  name: String!

}

input UpdateSettingInput {
  id: ID!
  name: String

}


