type Ticket {
  id: ID
  code: String
  firstName: String
  lastName: String
  email: String
  phone: String
  status: String
}

type Query {
  tickets: [Ticket!]
  findTicket(id: ID!): Ticket
}

type Mutation {
  createTicket(data: CreateTicketInput!): Ticket!
  deleteTicket(id: ID!): Boolean!
}

input CreateTicketInput {
  code: String
  firstName: String
  lastName: String
  email: String
  phone: String
  status: String
}