scalar DateTime

type Ticket {
  id: ID!
  code: String!
  firstName: String
  lastName: String
  email: String!
  phone: String
  status: Status
  service: Service!
  ticketLogs: [TicketLog!]!
  createdAt: DateTime
  updatedAt: DateTime
}

type TicketsPaginatedResult {
  items: [Ticket!]!
  totalCount: Int!
}

type Query {
  tickets(pagination: PaginationInput): TicketsPaginatedResult!
  ticket(id: ID!): Ticket
  ticketsByProperties(
    fields: TicketPropertiesInput
    pagination: PaginationInput
  ): TicketsPaginatedResult!

 ticketsForTVDisplay(pagination: PaginationInput, serviceId: ID): [Ticket]
}

type Mutation {
  generateTicket(data: GenerateTicketInput!): Ticket!
  deleteTicket(id: ID!): DeletedTicketResponse!
  updateTicket(data: UpdateTicketInput!): Ticket
  updateTicketStatus(data: UpdateStatusTicketInput!): Ticket!
}

type Subscription {
  ticketAdded: Ticket!
  ticketAddedByProperties(fields: TicketPropertiesInput): Ticket
}

type Subscription {
  ticketAdded: Ticket!
  ticketAddedByProperties(fields: TicketPropertiesInput): Ticket
}

enum Order {
  ASC
  DESC
}

input PaginationInput {
  cursor: String
  created: DateTime
  limit: Int
  order: Order
  offset: Int
}

input TicketPropertiesInput {
  firstName: String
  lastName: String
  email: String
  phone: String
  status: [Status!]
  serviceId: ID
  createdAt: DateTime
  updatedAt: DateTime
}

input UpdateStatusTicketInput {
  id: ID!
  status: Status!
}

input GenerateTicketInput {
  firstName: String @constraint(pattern: "^[a-zA-Zà-öø-ÿÀ-ÖØ-ß' -]{2,50}$", maxLength: 50, minLength: 2)
  lastName: String @constraint(pattern: "^[a-zA-Zà-öø-ÿÀ-ÖØ-ß' -]{2,50}$", maxLength: 50, minLength: 2)
  email: String! @constraint(format: "email", maxLength: 50)
  phone: String @constraint(pattern: "^[0-9]*$", maxLength: 15, minLength: 10)
  status: Status
  serviceId: ID!
}

input UpdateTicketInput {
  id: ID!
  code: String @constraint(pattern: "^[0-9a-zA-Z-]*$", maxLength: 50, minLength: 3)
  firstName: String @constraint(pattern: "^[a-zA-Zà-öø-ÿÀ-ÖØ-ß' -]{2,50}$", maxLength: 50, minLength: 2)
  lastName: String @constraint(pattern: "^[a-zA-Zà-öø-ÿÀ-ÖØ-ß' -]{2,50}$", maxLength: 50, minLength: 2)
  email: String @constraint(format: "email", maxLength: 50)
  phone: String @constraint(pattern: "^[0-9]*$", maxLength: 15, minLength: 10)
  status: Status
  serviceId: ID 
}

type DeletedTicketResponse {
  success: Boolean!
  message: String
}

enum Status {
  CREATED
  CANCELED
  DONE
  PENDING
  ARCHIVED
  INPROGRESS
  DELETED
}

# ============================================================================
#  SUBSCRIPTIONS (WebSocket)
# ============================================================================
type Subscription {
  ticketAdded: Ticket!
  ticketCreated: Ticket!
  ticketUpdated: Ticket!
  ticketStatusChanged(ticketId: ID!): Ticket!
  ticketDeleted: ID!
  ticketsChanged: Ticket!
}
