name: Backend PR Checks

on:
  [workflow_call, pull_request]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: utilisateur
          POSTGRES_PASSWORD: password
          POSTGRES_DB: nextone-db-test
        ports:
          - 5436:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: Run codegen
        run: npm run ci-codegen
      - name: Run tests
        run: npm run ci-test