name: Backend PR Checks

on: pull_request

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Go to backend and run tests
        run: npm i && npm run ci-test